### ISSUE TITLE
src/index.js broken

### ISSUE THREAD

**Issue by williamgrosset** [anaibol/phaser-webpack-babel-boilerplate#2]
Hi,

> window.game = new Game(config.SCREEN_WIDTH, conofig.SCREEN_HEIGHT)

This boilerplate has a spelling mistake found in index.js that doesn't allow the game window to be configured properly. The line should be as follows:

> window.game = new Game(config.SCREEN_WIDTH, config.SCREEN_HEIGHT)

Thanks. 👍

**Comment by anaibol** [comment]
Hey! Thanks! Sorry I am just seeing this. Fixed
